[AAE-11712] Validate models name while saving
Activiti/activiti-cloud pull request #1006
Opened 2023-02-15 11:41 UTC by graric

2023-02-15 11:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Activiti/activiti-cloud?pullRequest=1006) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Activiti/activiti-cloud?pullRequest=1006) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Activiti/activiti-cloud?pullRequest=1006) it.</sub>

2023-02-15 15:01 UTC, pmartinezga commented
Take a look at the build, it looks like your changes are collapsing with other existing tests

2023-02-16 17:51 UTC, pmartinezga reviewed
It is surprising for me that we had tests covering the case of using underscore and using capital letters I need to investigate this before merging

2023-03-06 15:38 UTC, pmartinezga approved these changes

2023-03-06 15:38 UTC, pmartinezga commented on activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-rest/src/main/java/org/activiti/cloud/services/modeling/rest/controller/ModelingRestExceptionHandler.java
> +    }
You are doing the same as the previous exception handler so I think it is better to merge the three we have for sending the conflict like this
```java
@ExceptionHandler({
    ModelNameConflictException.class,
    ModelNameInvalidException.class,
    ModelScopeIntegrityException.class
})
```

2023-03-06 15:39 UTC, pmartinezga requested changes
asking request just because the mergify bot will merge this otherwise

2023-03-07 12:37 UTC, pmartinezga approved these changes

2023-03-07 13:57 UTC, merged

2023-03-07 14:27 UTC, graric commented
Ref: https://github.com/Activiti/Activiti/issues/4273