Dev rkumar aae 9137 fix imported project version
Activiti/activiti-cloud pull request #1104
Opened 2023-05-31 10:18 UTC by RahulKumar1606

2023-06-01 07:20 UTC, matteo4diani commented
The business logic looks good 👍🏼 Can you add unit tests and, if it's an easy win, also integration tests? Try to add them to pre-existing test classes to simplify your work 🙏🏼

2023-06-01 07:20 UTC, matteo4diani requested changes
The business logic looks good 👍🏼 Can you add unit tests and, if it's an easy win, also integration tests? Try to add them to pre-existing test classes to simplify your work 🙏🏼

2023-06-01 08:04 UTC, miguelruizdev requested changes
Code looks alright.
Some requests on the pull request itself:
* Try to add a concise description of your changes when you open your draft/PR (a concise summary of the ticket will do just fine)
* Check [this guide](https://alfresco.atlassian.net/wiki/spaces/AP/pages/470909/How+to+commit+and+create+a+PR+in+Activiti) on how to proceed when committing on community projects (the community outside does not have access to our private Jira, so we need to referece a duplicated issue on the community repos that you have to create.
* Make sure that your commits are signed, otherwise you will not be able to merge due to security checks. You can follow [this guide](https://alfresco.atlassian.net/wiki/spaces/GUIL/pages/925402128/Signing+commits)

2023-06-15 10:31 UTC, matteo4diani requested changes

2023-06-15 10:31 UTC, matteo4diani commented on activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-service/src/test/java/org/activiti/cloud/services/modeling/service/ProjectServiceImplTest.java
> +import static org.junit.jupiter.api.Assertions.*;
Revert all the wildcard imports and check your IDE settings, when optimising imports IntelliJ must default to single class import -> https://www.jetbrains.com/help/idea/creating-and-optimizing-imports.html#disable-wildcard-imports

2023-06-15 13:56 UTC, matteo4diani approved these changes
LGTM 👍🏼 Great job @RahulKumar1606

2023-06-19 09:32 UTC, miguelruizdev approved these changes
LGTM! congrats on your first PR!

2023-06-21 07:43 UTC, merged