[AAE-2549] Incorrect response when completing task using the same correlation key for Intermediate Message Event
Activiti/activiti-cloud pull request #1116
Opened 2023-06-13 09:53 UTC by AkhileshPamidimarthi

Earlier when same value was being passed in the text field of the form. We were getting status code as 500(Internal Server Error).
This fix resolved this issue and now generating the status code as 409(Conflict).

https://github.com/Activiti/Activiti/issues/4347

2023-06-13 09:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Activiti/activiti-cloud?pullRequest=1116) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Activiti/activiti-cloud?pullRequest=1116) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Activiti/activiti-cloud?pullRequest=1116) it.</sub>

2023-06-13 10:16 UTC, miguelruizdev commented
Please, provide a description of the changes and commit according to this guide: https://alfresco.atlassian.net/wiki/spaces/HXP/pages/1281163265/How+to+commit+and+create+a+PR+in+Activiti+GitHub+Organization

2023-06-15 08:10 UTC, matteo4diani requested changes

2023-06-15 08:10 UTC, matteo4diani commented on activiti-cloud-acceptance-scenarios/runtime-acceptance-tests/src/main/java/org/activiti/cloud/qa/story/ProcessInstanceMessages.java
> +import static org.activiti.cloud.acc.core.assertions.RestErrorAssert.*;
Revert all the wildcard imports and check your IDE settings, when optimising imports IntelliJ must default to single class import -> https://www.jetbrains.com/help/idea/creating-and-optimizing-imports.html#disable-wildcard-imports

2023-06-15 08:10 UTC, matteo4diani commented on activiti-cloud-runtime-bundle-service/activiti-cloud-services-runtime-bundle/activiti-cloud-services-rest-impl/src/main/java/org/activiti/cloud/services/rest/controllers/RuntimeBundleExceptionHandler.java
> +import static org.springframework.http.HttpStatus.*;
Revert this to single-class imports

2023-06-15 10:27 UTC, matteo4diani approved these changes
LGTM 👍🏼 Good job @AkhileshPamidimarthi

2023-06-19 09:41 UTC, miguelruizdev approved these changes
LGTM! Congrats on your first PR!

2023-06-21 08:38 UTC, merged