[AAE-2673] Enable global models in database
Activiti/activiti-cloud pull request #113
Opened 2020-06-01 06:57 UTC by pmartinezga

Enable models to belong to more than one project by setting the current OneToMany relationship between project and models to ManyToMany

2020-06-10 13:11 UTC, erdemedeiros requested changes
Hi @pmartinezga. He is my feedback.

2020-06-10 13:11 UTC, erdemedeiros commented on activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-api-impl/src/main/java/org/activiti/cloud/modeling/api/impl/ModelImpl.java
> +            if(!projects.contains(project)){
This `if` is not necessary because `Set.add` is already checking for duplicates.

2020-06-10 13:11 UTC, erdemedeiros commented on activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-api-impl/src/main/java/org/activiti/cloud/modeling/api/impl/ModelImpl.java
> +        if(projects.contains(project)) {
Unnecessary check: `remove` has no effect if the element is not present in the set.

2020-06-10 13:11 UTC, erdemedeiros commented on activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-api-impl/src/main/java/org/activiti/cloud/modeling/api/impl/ModelImpl.java
> +            if (projects == null) {
Can `projects` be null? in this case, the same check should be applied in the method `remove project`?

2020-06-10 13:11 UTC, erdemedeiros commented on activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-repository/src/main/java/org/activiti/cloud/modeling/repository/ModelRepository.java
> +    Optional<M> getModelByNameInProject(P project, String modelName, String modelTypeFilter);
Maybe it's better to name the method `findModelByNameInProject` to keep the same pattern as `findModelById`.

2020-06-10 13:11 UTC, erdemedeiros commented on activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-rest/src/test/java/org/activiti/cloud/services/modeling/rest/controller/ModelControllerIT.java
>  @DirtiesContext(classMode = AFTER_EACH_TEST_METHOD)
I know that this code is not introduced by your PR, but would you mind to take the advantage that you're adding new tests to it and remove `(classMode = AFTER_EACH_TEST_METHOD)` from `@DirtiesContext`? It will reduce a lot the time we spent running this test. You can use the repositories to clean up the data, as I did [here](https://github.com/Activiti/activiti-cloud/pull/55/commits/1f4a0176fb0f5a8c74d4313c1b5ecd8caa78111a#diff-d74bc46e97ed5a279aba677fc44d57b9R118-R119).

2020-06-10 13:11 UTC, erdemedeiros commented on activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-rest/src/test/java/org/activiti/cloud/services/modeling/rest/controller/ModelValidationControllerIT.java
Same here: If you can remove `(classMode = AFTER_EACH_TEST_METHOD)` from `@DirtyContext` that would be great.

2020-06-10 13:11 UTC, erdemedeiros commented on activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-api-impl/src/main/java/org/activiti/cloud/modeling/api/impl/ModelImpl.java
>      public String getProjectId() {
It sounds strange to me to have both `getProjectId` and `getProjectsId`. I'd go with only `getProjectsId` and even this one I'm wondering if it's really necessary. Do you know how it's used? I mean if it's for the rest endpoint I'd expect to have one endpoint `/models/{modelId}` that returns only the direct properties of a model and a second endpoint `/models/{modelId}/projects` in case we need to retrieve information about the related projects. Maybe I'm missing something. I'm not very familiar with this part of the code.

2020-06-15 16:32 UTC, pmartinezga commented on activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-api-impl/src/main/java/org/activiti/cloud/modeling/api/impl/ModelImpl.java
>      public String getProjectId() {
This is only for retro-compatibility. The modeling app has been changed accordingly to use this new `getProjects` but I wasn't sure if there are more applications that could be affected by this change. 

Until this moment, a model had no sense if it is not in a project and could only belong to one and all the REST endpoints are aligned with that (for example the way of retrieving models were always through the project `/projects/{projectId}/models`)

We didn't want to introduce a disruptive change that made all the former stuff to stop working and redesign all the REST API.

2020-06-15 16:32 UTC, pmartinezga commented on activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-rest/src/test/java/org/activiti/cloud/services/modeling/rest/controller/ModelValidationControllerIT.java
👍

2020-06-15 16:32 UTC, pmartinezga commented on activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-rest/src/test/java/org/activiti/cloud/services/modeling/rest/controller/ModelControllerIT.java
>  @DirtiesContext(classMode = AFTER_EACH_TEST_METHOD)
👍

2020-06-15 16:32 UTC, pmartinezga commented on activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-repository/src/main/java/org/activiti/cloud/modeling/repository/ModelRepository.java
> +    Optional<M> getModelByNameInProject(P project, String modelName, String modelTypeFilter);
👍

2020-06-15 16:32 UTC, pmartinezga commented on activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-api-impl/src/main/java/org/activiti/cloud/modeling/api/impl/ModelImpl.java
> +            if (projects == null) {
nice spot! Yes, it can be null.model

2020-06-15 16:32 UTC, pmartinezga commented on activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-api-impl/src/main/java/org/activiti/cloud/modeling/api/impl/ModelImpl.java
> +        if(projects.contains(project)) {
👍

2020-06-15 16:32 UTC, pmartinezga commented on activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-api-impl/src/main/java/org/activiti/cloud/modeling/api/impl/ModelImpl.java
> +            if(!projects.contains(project)){
👍

2020-06-15 16:34 UTC, pmartinezga commented
> Hi @pmartinezga. He is my feedback.

Thanks for the suggestions @erdemedeiros I tried to apply all of them. Please tell me if I can do anything else to improve the PR

2020-06-16 16:41 UTC, mteodori commented on activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-api-impl/src/main/java/org/activiti/cloud/modeling/api/impl/ModelImpl.java
>      public String getProjectId() {
projectIds is better as a plural, API changes are ok, if there is impact agree with API consumers i.e. modeling-app and deployment and related acceptance/e2e tests

2020-06-16 17:48 UTC, pmartinezga commented on activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-api-impl/src/main/java/org/activiti/cloud/modeling/api/impl/ModelImpl.java
>      public String getProjectId() {
Removed and fixed the misspelling in the plural. Thanks!

2020-06-17 10:00 UTC, erdemedeiros approved these changes
LGTM

2020-06-17 10:22 UTC, mmartinadanx approved these changes

2020-06-17 10:26 UTC, merged