[AAE-17239] Added a check for uploading file
Activiti/activiti-cloud pull request #1238
Opened 2023-11-01 06:33 UTC by AkhileshPamidimarthi

2023-11-01 06:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Activiti/activiti-cloud?pullRequest=1238) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Activiti/activiti-cloud?pullRequest=1238) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Activiti/activiti-cloud?pullRequest=1238) it.</sub>

2023-11-02 08:52 UTC, jesty requested changes

2023-11-02 08:52 UTC, jesty commented on activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-rest/src/main/java/org/activiti/cloud/services/modeling/rest/controller/ModelController.java
> +        if (file.getSize() > 1024 * 1024 * 10) {
please replace the number (1024*1024*10) with a property using @Value annotation

@Value("${activiti.modeling.maxModelFileSize:10485760}")
private long maxModelFileSize;

2023-11-02 09:31 UTC, mavotto requested changes

2023-11-02 09:31 UTC, mavotto commented on activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-rest/src/main/java/org/activiti/cloud/services/modeling/rest/controller/ModelController.java
> +    @Value("${activiti.modeling.maxModelFileSize:1024102410}")
The value should be 1048576

2023-11-02 09:33 UTC, AkhileshPamidimarthi commented on activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-rest/src/main/java/org/activiti/cloud/services/modeling/rest/controller/ModelController.java
> +    @Value("${activiti.modeling.maxModelFileSize:1024102410}")
there is *10 too right

2023-11-02 10:30 UTC, jesty approved these changes
LGTM

2023-11-02 11:25 UTC, mavotto approved these changes

2023-11-02 11:26 UTC, merged