AAE-22469 Add new index in the Audit-event table
Activiti/activiti-cloud pull request #1437
Opened 2024-05-09 15:21 UTC by mavotto

this PR fixes: https://github.com/Activiti/Activiti/issues/4651

2024-05-09 15:28 UTC, eromano approved these changes

2024-05-09 17:18 UTC, jesty approved these changes
LGTM

2024-05-10 11:07 UTC, eromano requested changes
add the CONCURRENTLY please

2024-05-10 13:46 UTC, eromano approved these changes

2024-05-13 15:30 UTC, merged