[AAE-22377] Implemented max items limit per request
Activiti/activiti-cloud pull request #1440
Opened 2024-05-13 10:43 UTC by RCorsaletti

STILL WP need parameters for max and enabled/disabled

2024-05-13 15:15 UTC, graric commented on activiti-cloud-service-common/activiti-cloud-services-dbp-rest/src/main/java/org/activiti/cloud/alfresco/argument/resolver/AlfrescoPageArgumentMethodResolver.java
> +    private static final boolean MAX_ITEMS_LIMIT_ENABLED = true; // add parameter
Are these comments needed?

2024-05-13 15:17 UTC, graric commented on activiti-cloud-service-common/activiti-cloud-services-dbp-rest/src/main/java/org/activiti/cloud/alfresco/argument/resolver/AlfrescoPageArgumentMethodResolver.java
> +        if (isMaxItemsExceedingLimit && MAX_ITEMS_LIMIT_ENABLED) {
What if we move these lines into a method and just call it directly in the if? 
That way we can make it more readable IMO

2024-05-13 15:19 UTC, graric commented on activiti-cloud-query-service/activiti-cloud-services-query/activiti-cloud-services-query-rest/src/test/java/org/activiti/cloud/services/query/rest/TaskEntityControllerIT.java
> +    void findAllShouldReturnAllResultsUsingAlfrescoMetadataWhenMediaTypeIsApplicationJson() throws Exception {
Can you please follow the test naming convention? 🙏 

https://hyland.atlassian.net/wiki/spaces/HXP/pages/1308014107/Studio+-+Coding+Style+Guidelines#Naming-and-other-test-conventions

2024-05-13 15:20 UTC, graric commented on activiti-cloud-query-service/activiti-cloud-services-query/activiti-cloud-services-query-rest/src/test/java/org/activiti/cloud/services/query/rest/TaskEntityControllerIT.java
> +    void findAllShouldReturnAllResultsUsingAlfrescoMetadataWhenMediaTypeIsApplicationJson() throws Exception {
Also, the public access modifier is no longer needed in JUnit 5 tests, which is great news!

2024-05-14 07:59 UTC, erdemedeiros requested changes
Hello, I think this change is going to be confusing for end users. Let's discuss about it.

2024-05-14 07:59 UTC, erdemedeiros commented on activiti-cloud-service-common/activiti-cloud-services-dbp-rest/src/main/java/org/activiti/cloud/alfresco/argument/resolver/AlfrescoPageArgumentMethodResolver.java
> +    private static final boolean MAX_ITEMS_LIMIT_ENABLED = true; // add parameter
I think both values should use system properties, so that they can be overridden if needed. I'd also use `false` as default value for `MAX_ITEMS_LIMIT_ENABLED`.

2024-05-14 07:59 UTC, erdemedeiros commented on activiti-cloud-service-common/activiti-cloud-services-dbp-rest/src/main/java/org/activiti/cloud/alfresco/argument/resolver/AlfrescoPageArgumentMethodResolver.java
> +        if (isMaxItemsExceedingLimit && MAX_ITEMS_LIMIT_ENABLED) {
+1

2024-05-14 07:59 UTC, erdemedeiros commented on activiti-cloud-service-common/activiti-cloud-services-dbp-rest/src/main/java/org/activiti/cloud/alfresco/argument/resolver/AlfrescoPageArgumentMethodResolver.java
> +            return new AlfrescoPageRequest(MAX_ITEMS_LIMIT + 1L, MAX_ITEMS_LIMIT, limitedPageable);
IMO, silently changing the values provided via query param sounds confusing to me and I think people will report bugs for this. Maybe it's better to raise an exception in this case.

2024-05-14 07:59 UTC, erdemedeiros commented on activiti-cloud-query-service/activiti-cloud-services-query/activiti-cloud-services-query-rest/src/test/java/org/activiti/cloud/services/query/rest/TaskEntityControllerIT.java
> +    }
In any case, we should never touch to `skipCount` that gives how many elements should be left behind before getting the first element to be returned (this is the equivalent of start index). In this specific case, the caller is asking for up to `2000` elements, skipping the first 2001 elements from the results, but what he's getting in return is up `1000` (what could still be fine), skipping only the first 1001 elements from the results: he's getting 1000 elements that he's not expecting.

2024-05-24 10:30 UTC, closed without merging