ACA-3943 - added /assign to TaskController
Activiti/activiti-cloud pull request #200
Opened 2020-09-14 15:55 UTC by Giovanni007

Depends on [PR #3340](https://github.com/Activiti/Activiti/pull/3440)
Allow end-user to reassign task using the added API /v1/tasks/{taskId}/assign

2020-09-21 13:16 UTC, ffazzini approved these changes

2020-09-21 13:23 UTC, miguelruizdev approved these changes

2020-09-21 14:13 UTC, erdemedeiros approved these changes
In addition to the tests that you have already that are covering the controller only, you also need to add one integration test in [TasksIT](https://github.com/Activiti/activiti-cloud/blob/develop/activiti-cloud-runtime-bundle-service/activiti-cloud-starter-runtime-bundle/src/test/java/org/activiti/cloud/starter/tests/runtime/TasksIT.java).

2020-09-21 14:13 UTC, erdemedeiros commented on activiti-cloud-runtime-bundle-service/activiti-cloud-services-runtime-bundle/activiti-cloud-services-rest-impl/src/main/java/org/activiti/cloud/services/rest/controllers/TaskControllerImpl.java
> +        if (assignTaskPayload!=null)
Please, always use brackets around `if` body, even when it has a single line.

2020-09-21 14:16 UTC, erdemedeiros requested changes
Oups, I clicked in the wrong button in my previous comment :D

2020-09-22 08:35 UTC, erdemedeiros approved these changes

2020-09-22 08:47 UTC, merged