Activiti/Activiti#3460-Added CloudApplicationDeployedProducer
Activiti/activiti-cloud pull request #238
Opened 2020-11-13 14:48 UTC by Giovanni007

Application deloyed events are not triggered when rb starts. This PR try to fix the issue

2020-11-13 15:47 UTC, andrea-ligios approved these changes
LGTM

2020-11-16 09:09 UTC, erdemedeiros requested changes
Good catch! It's only missing the related integration test.

2020-11-16 09:09 UTC, erdemedeiros commented on activiti-cloud-runtime-bundle-service/activiti-cloud-services-runtime-bundle/activiti-cloud-services-events/src/test/java/org/activiti/cloud/services/events/listeners/CloudApplicationDeployedProducerTest.java
> +    public void shouldSendMessageWithDeployedApplicationWhenWebApplicationTypeIsServlet() {
The suffix `WhenWebApplicationTypeIsServlet` seems wrong here as we are not checking the web application type in the code. I think can rename it to `should_sendMessageWithDeployedApplication`.

2020-11-16 09:09 UTC, erdemedeiros commented on activiti-cloud-runtime-bundle-service/activiti-cloud-services-runtime-bundle/activiti-cloud-services-events/src/test/java/org/activiti/cloud/services/events/listeners/CloudApplicationDeployedProducerTest.java
> +public class CloudApplicationDeployedProducerTest {
You also need to add an integration test covering the producer, similar to [this one](https://github.com/Activiti/activiti-cloud/blob/develop/activiti-cloud-runtime-bundle-service/activiti-cloud-starter-runtime-bundle/src/test/java/org/activiti/cloud/starter/tests/services/audit/AuditProducerIT.java#L161).

2020-11-16 10:29 UTC, erdemedeiros approved these changes
LGTM

2020-11-16 10:56 UTC, merged