[DW-1665] - added new api call to start created process
Activiti/activiti-cloud pull request #37
Opened 2020-04-06 16:58 UTC by VitoAlbano

2020-04-06 20:12 UTC, VitoAlbano commented
https://github.com/Activiti/Activiti/issues/3225

2020-04-06 20:12 UTC, VitoAlbano commented
Wating for https://github.com/Activiti/Activiti/pull/3224

2020-04-08 11:23 UTC, erdemedeiros requested changes

2020-04-08 11:23 UTC, erdemedeiros commented on activiti-cloud-runtime-bundle-service/activiti-cloud-services-runtime-bundle/activiti-cloud-services-rest-impl/src/test/java/org/activiti/cloud/services/rest/controllers/ProcessInstanceControllerImplIT.java
> +            .andDo(document(DOCUMENTATION_IDENTIFIER + "/create"));
I think this should be `/start-created` instead of `/created`.

2020-04-08 11:23 UTC, erdemedeiros commented on activiti-cloud-runtime-bundle-service/activiti-cloud-starter-runtime-bundle/src/test/java/org/activiti/cloud/starter/tests/runtime/ProcessInstanceIT.java
> +        assertThatExceptionOfType(RestClientException.class).isThrownBy(() ->
This sounds wrong to me. You should not be getting any exception, only an HTTP status code that is indicating a problem.

2020-04-09 07:50 UTC, erdemedeiros commented on activiti-cloud-runtime-bundle-service/activiti-cloud-services-runtime-bundle/activiti-cloud-services-rest-impl/src/test/java/org/activiti/cloud/services/rest/controllers/ProcessInstanceControllerImplIT.java
> +            .content(mapper.writeValueAsString(cmd)))
Actually, I think this is wrong. This endpoint does not need any payload, right? it's only a post on the process instance id.

2020-04-09 08:32 UTC, erdemedeiros approved these changes

2020-04-09 11:13 UTC, merged