fix(GH-3674): aggregate CloudIntegrationRequestedEvent during connector task execution
Activiti/activiti-cloud pull request #450
Opened 2021-07-02 21:00 UTC by igdianov

2021-07-29 12:58 UTC, erdemedeiros requested changes
I have some concerns about `CompositeCommand`. LGTM otherwise.

2021-07-29 12:58 UTC, erdemedeiros commented on activiti-cloud-runtime-bundle-service/activiti-cloud-services-runtime-bundle/activiti-cloud-services-connectors/src/main/java/org/activiti/services/connectors/channel/CompositeCommand.java
> +class CompositeCommand extends ArrayList<Command<?>> implements Command<Void> {
I'd prefer not to have `CompositeCommand` extending `ArrayList`, I'd rather receive a list of commands in the constructor and maybe add a utility method to initialize it:
```java
CompositeCommand.of(new Command1(), new Command2())
```

2021-07-29 12:58 UTC, erdemedeiros commented on activiti-cloud-runtime-bundle-service/activiti-cloud-services-runtime-bundle/activiti-cloud-services-connectors/src/main/java/org/activiti/services/connectors/channel/ServiceTaskIntegrationErrorEventHandler.java
> +                            return;
I was wondering if we can avoid this `return`.

2021-07-30 16:20 UTC, erdemedeiros approved these changes

2021-08-04 05:38 UTC, igdianov commented on activiti-cloud-runtime-bundle-service/activiti-cloud-services-runtime-bundle/activiti-cloud-services-connectors/src/main/java/org/activiti/services/connectors/channel/CompositeCommand.java
> +class CompositeCommand extends ArrayList<Command<?>> implements Command<Void> {
fixed

2021-08-04 06:20 UTC, merged

2021-08-04 17:53 UTC, igdianov commented on activiti-cloud-runtime-bundle-service/activiti-cloud-services-runtime-bundle/activiti-cloud-services-connectors/src/main/java/org/activiti/services/connectors/channel/CompositeCommand.java
> +class CompositeCommand extends ArrayList<Command<?>> implements Command<Void> {
sounds good