fix: Improve message event handling when there are several runtime bundles
Activiti/activiti-cloud pull request #461
Opened 2021-08-06 05:47 UTC by igdianov

deployed using the same process definition but sharing one Rabbit MQ

2021-08-11 16:33 UTC, erdemedeiros requested changes
Some minor details. LGTM otherwise.

2021-08-11 16:33 UTC, erdemedeiros commented on activiti-cloud-messages-service/integration-tests/src/test/java/org/activiti/cloud/messages/integration/tests/rb/MultipleRbMessagesIT.java
> +    private static ConfigurableApplicationContext rbCtx2;
Would you mind renaming the variables to `h2Context`, `rbContext1` and `rbContext2`?

2021-08-11 16:33 UTC, erdemedeiros commented on activiti-cloud-messages-service/integration-tests/src/test/java/org/activiti/cloud/messages/integration/tests/rb/MultipleRbMessagesIT.java
> +        new RabbitMQContainer("rabbitmq:3.8.9-management-alpine");
Is it possible to reuse `RabbitMQContainerApplicationInitializer` and `KeycloakContainerApplicationInitializer`, here?

2021-08-11 16:33 UTC, erdemedeiros commented on activiti-cloud-runtime-bundle-service/activiti-cloud-starter-runtime-bundle/src/test/java/org/activiti/cloud/starter/tests/conf/EngineConfigurationIT.java
> +        assertProperty("spring.cloud.stream.bindings.signalProducer.destination").isEqualTo("signalEvent");
Should we add the suffix to `signalEvent` as well?

2021-08-11 16:33 UTC, erdemedeiros commented on activiti-cloud-runtime-bundle-service/activiti-cloud-starter-runtime-bundle/src/test/java/org/activiti/cloud/starter/tests/conf/EngineConfigurationIT.java
> +    }
Really nice to have these extra tests here!

2021-08-11 18:13 UTC, igdianov commented on activiti-cloud-runtime-bundle-service/activiti-cloud-starter-runtime-bundle/src/test/java/org/activiti/cloud/starter/tests/conf/EngineConfigurationIT.java
> +        assertProperty("spring.cloud.stream.bindings.signalProducer.destination").isEqualTo("signalEvent");
I think it is out of the scope for this PR.

2021-08-11 18:13 UTC, igdianov commented on activiti-cloud-runtime-bundle-service/activiti-cloud-starter-runtime-bundle/src/test/java/org/activiti/cloud/starter/tests/conf/EngineConfigurationIT.java
> +    }
👍

2021-08-11 18:14 UTC, igdianov commented on activiti-cloud-messages-service/integration-tests/src/test/java/org/activiti/cloud/messages/integration/tests/rb/MultipleRbMessagesIT.java
> +    private static ConfigurableApplicationContext rbCtx2;
Fixed.

2021-08-11 18:26 UTC, igdianov commented on activiti-cloud-messages-service/integration-tests/src/test/java/org/activiti/cloud/messages/integration/tests/rb/MultipleRbMessagesIT.java
> +        new RabbitMQContainer("rabbitmq:3.8.9-management-alpine");
I thought about it and tried to use common test containers. It failed. The reason is that application configuration is not SpringBootTest and ContextConfiguration is completely ignored in this case.

2021-08-12 10:00 UTC, erdemedeiros approved these changes
LGMT!

2021-08-12 10:53 UTC, merged