fix(GH-3702): use activiti.cloud.application.name scope for Rb channel binding destinations
Activiti/activiti-cloud pull request #471
Opened 2021-08-26 03:04 UTC by igdianov

This PR fixes Rb channel destinations to use `activiti.cloud.application.name` property for the channel bindings in order for all services to share the same `activiti.cloud.application.name` and to be able to communicate correctly via Spring Cloud Stream messaging broker, i.e.

- [x] New common `activiti.cloud.messaging.destination-separator` configuration property has been added to enable customization of the destination separator character, i.e. `.` or `_` for Rb destinations. The default separator value is set to `_`.
- [x] Connector Integration Result Destination, i.e. `integrationResult_${activiti.cloud.application.name}`
- [x] Connector Integration Error Destination, i.e. `integrationError_${activiti.cloud.application.name}`
- [x] Command Consumer Destination, i.e. `commandConsumer_${activiti.cloud.application.name}`
- [x] Async Job Executor Destination, i.e. `asyncJobExecutor_${activiti.cloud.application.name}`
- [x] Message Events Destination, i.e. `messageEvents_${activiti.cloud.application.name}`
- [x] Message Events Input Destination, i.e. `messageEvents_${activiti.cloud.application.name}`
- [x] Message Events Output Destination, i.e. `commandConsumer_${activiti.cloud.application.name}`

Part of https://github.com/Activiti/Activiti/issues/3702

2021-08-26 13:43 UTC, erdemedeiros requested changes
Shouldn't we use `activiti.cloud.mq.destination.separator` everywhere?

2021-08-26 13:43 UTC, erdemedeiros commented on activiti-cloud-connectors/activiti-cloud-starter-connector/src/main/java/org/activiti/cloud/connectors/starter/channels/IntegrationResultDestinationBuilderImpl.java
>          String resultDestinationOverride = connectorProperties.getErrorDestinationOverride();
Shouldn't this be using `getResultDestinationOverride()` instead of `getErrorDestinationOverride()`?

2021-08-26 13:43 UTC, erdemedeiros commented on activiti-cloud-messages-service/services/core/src/main/java/org/activiti/cloud/services/messages/core/router/CommandConsumerDestinationMapper.java
>          return new StringBuilder("commandConsumer").append("_")
It should use the value of `activiti.cloud.mq.destination.separator` property, instead of hard coded `_` character.

2021-08-26 13:43 UTC, erdemedeiros commented on activiti-cloud-messages-service/services/core/src/main/resources/config/activiti-cloud-services-messages-core.properties
> +spring.cloud.stream.bindings.input.destination=messageEvents_${activiti.cloud.application.name}
It should use `activiti.cloud.mq.destination.separator` property.

2021-08-26 13:43 UTC, erdemedeiros commented on activiti-cloud-messages-service/services/core/src/main/resources/config/activiti-cloud-services-messages-core.properties
> +spring.cloud.stream.bindings.output.destination=commandConsumer_${activiti.cloud.application.name}
`activiti.cloud.mq.destination.separator`

2021-08-26 13:43 UTC, erdemedeiros commented on activiti-cloud-runtime-bundle-service/activiti-cloud-services-runtime-bundle/activiti-cloud-services-job-executor/src/main/java/org/activiti/cloud/services/job/executor/MessageBasedJobManager.java
> +                                  .append("_")
`activiti.cloud.mq.destination.separator`

2021-08-26 13:43 UTC, erdemedeiros commented on activiti-cloud-runtime-bundle-service/activiti-cloud-starter-runtime-bundle/src/test/java/org/activiti/cloud/starter/tests/runtime/ServiceTaskConsumerHandler.java
> +            .resolveDestination("integrationResult_" + runtimeBundleProperties.getAppName())
`activiti.cloud.mq.destination.separator`

2021-08-27 07:00 UTC, igdianov commented on activiti-cloud-messages-service/services/core/src/main/java/org/activiti/cloud/services/messages/core/router/CommandConsumerDestinationMapper.java
>          return new StringBuilder("commandConsumer").append("_")
fixed

2021-08-27 07:00 UTC, igdianov commented on activiti-cloud-messages-service/services/core/src/main/resources/config/activiti-cloud-services-messages-core.properties
> +spring.cloud.stream.bindings.output.destination=commandConsumer_${activiti.cloud.application.name}
fixed

2021-08-27 07:00 UTC, igdianov commented on activiti-cloud-runtime-bundle-service/activiti-cloud-services-runtime-bundle/activiti-cloud-services-job-executor/src/main/java/org/activiti/cloud/services/job/executor/MessageBasedJobManager.java
> +                                  .append("_")
fixed

2021-08-27 07:00 UTC, igdianov commented on activiti-cloud-runtime-bundle-service/activiti-cloud-starter-runtime-bundle/src/test/java/org/activiti/cloud/starter/tests/runtime/ServiceTaskConsumerHandler.java
> +            .resolveDestination("integrationResult_" + runtimeBundleProperties.getAppName())
fixed

2021-08-27 07:00 UTC, igdianov commented on activiti-cloud-messages-service/services/core/src/main/resources/config/activiti-cloud-services-messages-core.properties
> +spring.cloud.stream.bindings.input.destination=messageEvents_${activiti.cloud.application.name}
fixed

2021-08-27 07:01 UTC, igdianov commented on activiti-cloud-connectors/activiti-cloud-starter-connector/src/main/java/org/activiti/cloud/connectors/starter/channels/IntegrationResultDestinationBuilderImpl.java
>          String resultDestinationOverride = connectorProperties.getErrorDestinationOverride();
fixed

2021-08-27 13:13 UTC, erdemedeiros commented on activiti-cloud-runtime-bundle-service/activiti-cloud-starter-runtime-bundle/src/test/java/org/activiti/cloud/starter/tests/runtime/ServiceTaskConsumerHandler.java
> +            .resolveDestination("integrationResult_" + runtimeBundleProperties.getAppName())
It seems you forgot to push this one.

2021-08-27 14:22 UTC, igdianov commented on activiti-cloud-runtime-bundle-service/activiti-cloud-starter-runtime-bundle/src/test/java/org/activiti/cloud/starter/tests/runtime/ServiceTaskConsumerHandler.java
> +            .resolveDestination("integrationResult_" + runtimeBundleProperties.getAppName())
fixed

2021-08-27 14:36 UTC, erdemedeiros approved these changes
LGTM!

2021-08-27 15:07 UTC, merged