fix(GH-3734): Support ability to configure topics on shared message broker instance
Activiti/activiti-cloud pull request #485
Opened 2021-10-02 01:12 UTC by igdianov

2021-10-13 16:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Activiti/activiti-cloud?pullRequest=485) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Activiti/activiti-cloud?pullRequest=485) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Activiti/activiti-cloud?pullRequest=485) it.</sub>

2021-10-21 15:18 UTC, erdemedeiros requested changes
Igor, you can find my feedback below (don't forget to click on the button "Load more" as there will be hidden comments).
One of my main question is about the removal of the suffixes for destinations that has been added during the latest release and documented in the [release notes](https://activiti.gitbook.io/activiti-7-developers-guide/releases/7.1.0-m15#changes-from-previous-milestones).

2021-10-21 15:18 UTC, erdemedeiros commented on activiti-cloud-connectors/activiti-cloud-starter-connector/src/main/java/org/activiti/cloud/connectors/starter/channels/IntegrationErrorDestinationBuilderImpl.java
> +    protected String getServiceDestination(IntegrationRequest event) {
Access can be private.

2021-10-21 15:18 UTC, erdemedeiros commented on activiti-cloud-connectors/activiti-cloud-starter-connector/src/test/java/org/activiti/cloud/connectors/starter/channels/IntegrationErrorDestinationBuilderTest.java
> +        initMocks(this);
`inittMocks` has been deprecated in the latest releases of Mockito. Prefer to annotate the test class with `@ExtendWith(MockitoExtension.class)` and `initMocks` can be removed.

2021-10-21 15:18 UTC, erdemedeiros commented on activiti-cloud-messages-service/services/core/src/main/resources/config/activiti-cloud-services-messages-core.properties
> +spring.cloud.stream.bindings.messageConnectorInput.group=messages
Should we mention the change in the name of the binding in the release notes or it's better to consider it as an implementation detail?

2021-10-21 15:18 UTC, erdemedeiros commented on activiti-cloud-messages-service/services/core/src/main/resources/config/activiti-cloud-services-messages-core.properties
> +spring.cloud.stream.bindings.messageConnectorInput.destination=messageEvents
Is it normal that `${activiti.cloud.messaging.destination-separator}${activiti.cloud.application.name}` as been removed?

2021-10-21 15:18 UTC, erdemedeiros commented on activiti-cloud-messages-service/services/core/src/main/resources/config/activiti-cloud-services-messages-core.properties
> -spring.cloud.stream.bindings.output.destination=commandConsumer${activiti.cloud.messaging.destination-separator}${activiti.cloud.application.name}
Is it normal that `${activiti.cloud.messaging.destination-separator}${activiti.cloud.application.name}` has been removed?

2021-10-21 15:18 UTC, erdemedeiros commented on activiti-cloud-notifications-graphql-service/services/events/src/main/resources/META-INF/graphql-events.properties
> -spring.cloud.stream.bindings.graphQLEngineEventsConsumerSource.destination=${ACT_NOTIFICATIONS_GRAPHQL_ENGINE_VENTS_CONSUMER_DESTINATION:engineEvents}
Is it normal that `ACT_NOTIFICATIONS_GRAPHQL_ENGINE_VENTS_CONSUMER_DESTINATION` has been removed?

2021-10-21 15:18 UTC, erdemedeiros commented on activiti-cloud-runtime-bundle-service/activiti-cloud-services-runtime-bundle/activiti-cloud-services-connectors/src/main/java/org/activiti/services/connectors/IntegrationRequestSender.java
> +        IntegrationRequestImpl.class.cast(event).setErrorDestination(errorDestination);
This cast doesn't smell good. Wouldn't it be better to set the result and error destinations directly in the place where the integration request is created in `MQServiceTaskBehavior`?

2021-10-21 15:18 UTC, erdemedeiros commented on activiti-cloud-runtime-bundle-service/activiti-cloud-services-runtime-bundle/activiti-cloud-services-connectors/src/main/resources/config/integration-result-stream.properties
> -spring.cloud.stream.bindings.integrationResultsConsumer.destination=${ACT_INT_RES_CONSUMER:integrationResult${activiti.cloud.mq.destination.separator}${spring.application.name}}
Is it normal that `ACT_INT_RES_CONSUMER` and `${activiti.cloud.mq.destination.separator}${spring.application.name}` has been removed?

2021-10-21 15:18 UTC, erdemedeiros commented on activiti-cloud-runtime-bundle-service/activiti-cloud-services-runtime-bundle/activiti-cloud-services-connectors/src/main/resources/config/integration-result-stream.properties
> +spring.cloud.stream.bindings.integrationErrorsConsumer.destination=integrationError
Same question here.

2021-10-21 15:18 UTC, erdemedeiros commented on activiti-cloud-runtime-bundle-service/activiti-cloud-services-runtime-bundle/activiti-cloud-services-core/src/main/resources/config/command-endpoint-channels.properties
> +spring.cloud.stream.bindings.commandResults.destination=${ACT_RB_COMMAND_RESULTS_DEST:commandResults}
Removal of suffix.

2021-10-21 15:18 UTC, erdemedeiros commented on activiti-cloud-runtime-bundle-service/activiti-cloud-services-runtime-bundle/activiti-cloud-services-job-executor/src/main/resources/config/job-executor-channel.properties
> -activiti.cloud.rb.job-executor.group=${spring.application.name}
Destination suffix.

2021-10-21 15:18 UTC, erdemedeiros commented on activiti-cloud-runtime-bundle-service/activiti-cloud-services-runtime-bundle/activiti-cloud-services-subscriptions/src/main/resources/config/signal-events-channels.properties
> +spring.cloud.stream.bindings.signalConsumer.destination=signalEvent
Removal of env variable name.

2021-10-21 15:18 UTC, erdemedeiros commented on activiti-cloud-runtime-bundle-service/activiti-cloud-services-runtime-bundle/messages-events/src/main/java/org/activiti/cloud/services/messages/events/config/MessageEventsAutoConfiguration.java
> +        String messageEventOutputDestination = bindingServiceProperties.getBindingDestination("commandConsumer");
Could reuse `ProcessEngineChannels.COMMAND_CONSUMER` instead of literal `"commandConsumer"`.

2021-10-21 15:18 UTC, erdemedeiros commented on activiti-cloud-runtime-bundle-service/activiti-cloud-services-runtime-bundle/messages-events/src/main/resources/config/messages-events-channels.properties
> -spring.cloud.stream.bindings.messageEvents.destination=messageEvents${activiti.cloud.messaging.destination-separator}${activiti.cloud.application.name}
Destination suffix.

2021-10-21 15:18 UTC, erdemedeiros commented on activiti-cloud-runtime-bundle-service/activiti-cloud-starter-runtime-bundle/src/main/java/org/activiti/cloud/starter/rb/configuration/ActivitiConnectorDestinationMappingStrategy.java
> +        return Optional.ofNullable(destinationTransformer.apply(implementation))
List of transformers?

2021-10-21 15:18 UTC, erdemedeiros commented on activiti-cloud-runtime-bundle-service/activiti-cloud-starter-runtime-bundle/src/test/java/org/activiti/cloud/starter/tests/conf/EngineConfigurationIT.java
> +                      entry("miCloudConnector", "namespace.micloudconnector"));
Note: it's possible to avoid instantiating `SimpleEntry` as following:
```java
         assertThat(bindings)
            .extractingFromEntries(
                Entry::getKey, entry -> entry.getValue().getDestination())
            .contains(tuple("mealsConnector", "namespace.mealsconnector"),
                      tuple("rest.GET", "namespace.rest.get"),
                      tuple("perfromBusinessTask", "namespace.perfrombusinesstask"),
                      tuple("anyImplWithoutHandler", "namespace.anyimplwithouthandler"),
                      tuple("payment", "namespace.payment"),
                      tuple("Constants Connector.constantsActionName", "namespace.constants-connector.constantsactionname"),
                      tuple("Variable Mapping Connector.variableMappingActionName", "namespace.variable-mapping-connector.variablemappingactionname"),
                      tuple("miCloudConnector", "namespace.micloudconnector"));
```

2021-10-21 15:18 UTC, erdemedeiros commented on activiti-cloud-runtime-bundle-service/activiti-cloud-starter-runtime-bundle/src/test/java/org/activiti/cloud/starter/tests/conf/EngineConfigurationIT.java
> +            .isEqualTo(new String[] {"query", "audit"});
It can be simplified to `.containsExactly("query", "audit");`

2021-10-21 15:18 UTC, erdemedeiros commented on activiti-cloud-runtime-bundle-service/activiti-cloud-starter-runtime-bundle/src/test/java/org/activiti/cloud/starter/tests/conf/EngineConfigurationIT.java
> +        assertThat(messageEventsOutput.getProducer().getRequiredGroups()).isEqualTo(new String[] {"messages"});
It can be simplified to `assertThat(messageEventsOutput.getProducer().getRequiredGroups()).containsExactly("messages");`

2021-10-21 15:18 UTC, erdemedeiros commented on activiti-cloud-runtime-bundle-service/activiti-cloud-starter-runtime-bundle/src/test/java/org/activiti/cloud/starter/tests/conf/EngineConfigurationIT.java
> +        assertThat(signalProducer.getProducer().getRequiredGroups()).isEqualTo(new String[] {"my-activiti-rb-app"});
It can be simplified.

2021-10-21 15:18 UTC, erdemedeiros commented on activiti-cloud-runtime-bundle-service/activiti-cloud-starter-runtime-bundle/src/test/java/org/activiti/cloud/starter/tests/runtime/MQServiceTaskIT.java
> +        assertThat(destinations).containsOnly("mealsConnector",
In this specific case, I think it's better to use `contains` instead of `containsOnly`. Otherwise, we'll need to update this test every time a new process containing a service task is added to the test base.

2021-10-21 15:18 UTC, erdemedeiros commented on activiti-cloud-service-common/activiti-cloud-service-messaging-config/pom.xml
> +      <optional>true</optional>
Is it normal to have this dependency as optional?

2021-10-21 15:18 UTC, erdemedeiros commented on activiti-cloud-service-common/activiti-cloud-service-messaging-config/src/main/java/org/activiti/cloud/common/messaging/config/ActivitiMessagingDestinationTransformer.java
> +public class ActivitiMessagingDestinationTransformer implements Function<String, String> {
It should be covered by unit tests, in addition to the integration tests that are already in place.

2021-10-21 15:18 UTC, erdemedeiros commented on activiti-cloud-runtime-bundle-service/activiti-cloud-starter-runtime-bundle/src/main/java/org/activiti/cloud/starter/rb/configuration/ActivitiConnectorDestinationMappingStrategy.java
> +                       .map(messagingProperties.overrideDestination())
I got confused here: `messagingProperties.overrideDestination()` is called here and inside `ActivitiMessagingDestinationTransformer.apply()`. Am I missing something?

2021-10-21 15:18 UTC, erdemedeiros commented on activiti-cloud-service-common/activiti-cloud-service-messaging-config/src/main/java/org/activiti/cloud/common/messaging/ActivitiCloudMessagingProperties.java
> +        return escapeIllegalCharacters().andThen(String::toLowerCase);
IMO, this logic should go directly inside the transformer and I'd see it as a list of transforms that the customer can option-in:
`activiti.cloud.messaging.destinationOverrideTransformers=scapeIllegalChars,toLowercase`. What do you think?

If we go with a list of transformers it could be done in another iteration (separated PR once this is merged).

2021-10-21 15:18 UTC, erdemedeiros commented on activiti-cloud-service-common/activiti-cloud-service-messaging-config/src/main/java/org/activiti/cloud/common/messaging/config/ActivitiMessagingDestinationsBeanPostProcessor.java
> +                               });
This block can be simplified using Map foreach:

```java
            bindingServiceProperties.getBindings()
                .forEach((bindingName, bindingProperties) -> {
                    String source = Optional.ofNullable(bindingProperties.getDestination())
                        .orElse(bindingName);

                    String destination = destinationTransformer.apply(source);

                    bindingProperties.setDestination(destination);

                    log.warn("Overriding destination '{}' for binding '{}'",
                        destination,
                        bindingName);
                });
```

2021-10-21 15:18 UTC, erdemedeiros commented on activiti-cloud-service-common/activiti-cloud-service-messaging-config/src/main/java/org/activiti/cloud/common/messaging/config/ActivitiMessagingDestinationsBeanPostProcessor.java
> +                                   log.warn("Overriding destination '{}' for binding '{}'",
Is `warn` the right level for this log? Shouldn't it be `info`? What do you think?

2021-10-21 15:18 UTC, erdemedeiros commented on activiti-cloud-service-common/activiti-cloud-service-messaging-config/src/test/java/org/activiti/cloud/common/messaging/config/test/ActivitiMessagingDestinationsEnvironmentPostProcessorDisabledTests.java
> +public class ActivitiMessagingDestinationsEnvironmentPostProcessorDisabledTests {
Prefer `IT` suffix as it's an integration test.

2021-10-21 15:18 UTC, erdemedeiros commented on activiti-cloud-service-common/activiti-cloud-service-messaging-config/src/test/java/org/activiti/cloud/common/messaging/config/test/ActivitiMessagingDestinationsEnvironmentPostProcessorDisabledTests.java
> +    "activiti.cloud.messaging.destinations.[camel-connector.INVOKE].name=${ACT_CAMEL_CONNECTOR_INVOKE_DEST:camel_connector_invoke}",
Can we still do an explicit override in addition to the override logic that's scaping illegal characters and setting everything to lowercase?

2021-10-21 15:18 UTC, erdemedeiros commented on activiti-cloud-service-common/activiti-cloud-service-messaging-config/src/test/java/org/activiti/cloud/common/messaging/config/test/ActivitiMessagingDestinationsEnvironmentPostProcessorTests.java
> +public class ActivitiMessagingDestinationsEnvironmentPostProcessorTests {
`IT` suffix.

2021-10-22 05:31 UTC, igdianov commented on activiti-cloud-connectors/activiti-cloud-starter-connector/src/main/java/org/activiti/cloud/connectors/starter/channels/IntegrationErrorDestinationBuilderImpl.java
> +    protected String getServiceDestination(IntegrationRequest event) {
fixed

2021-10-22 05:32 UTC, igdianov commented on activiti-cloud-connectors/activiti-cloud-starter-connector/src/test/java/org/activiti/cloud/connectors/starter/channels/IntegrationErrorDestinationBuilderTest.java
> +        initMocks(this);
fixed

2021-10-22 05:34 UTC, igdianov commented on activiti-cloud-messages-service/services/core/src/main/resources/config/activiti-cloud-services-messages-core.properties
> +spring.cloud.stream.bindings.messageConnectorInput.group=messages
It is internal implementation detail. We should not expose channel bindings for public knowledge

2021-10-22 05:37 UTC, igdianov commented on activiti-cloud-messages-service/services/core/src/main/resources/config/activiti-cloud-services-messages-core.properties
> +spring.cloud.stream.bindings.messageConnectorInput.destination=messageEvents
Yes, it is need for mapping Activiti messaging destinations configuration to channel destinations. The effective channel destination will be configured at runtime by BindingServiceProperties bean post processors.

2021-10-22 05:38 UTC, igdianov commented on activiti-cloud-messages-service/services/core/src/main/resources/config/activiti-cloud-services-messages-core.properties
> -spring.cloud.stream.bindings.output.destination=commandConsumer${activiti.cloud.messaging.destination-separator}${activiti.cloud.application.name}
Yes, see above description in the PR notes.

2021-10-22 05:42 UTC, igdianov commented on activiti-cloud-notifications-graphql-service/services/events/src/main/resources/META-INF/graphql-events.properties
> -spring.cloud.stream.bindings.graphQLEngineEventsConsumerSource.destination=${ACT_NOTIFICATIONS_GRAPHQL_ENGINE_VENTS_CONSUMER_DESTINATION:engineEvents}
Yes, see above description in the PR notes.

2021-10-22 05:51 UTC, igdianov commented on activiti-cloud-runtime-bundle-service/activiti-cloud-services-runtime-bundle/activiti-cloud-services-connectors/src/main/java/org/activiti/services/connectors/IntegrationRequestSender.java
> +        IntegrationRequestImpl.class.cast(event).setErrorDestination(errorDestination);
Makes sense. Fixed

2021-10-22 05:51 UTC, igdianov commented on activiti-cloud-runtime-bundle-service/activiti-cloud-services-runtime-bundle/activiti-cloud-services-connectors/src/main/resources/config/integration-result-stream.properties
> -spring.cloud.stream.bindings.integrationResultsConsumer.destination=${ACT_INT_RES_CONSUMER:integrationResult${activiti.cloud.mq.destination.separator}${spring.application.name}}
Yes, see note in the PR

2021-10-22 05:51 UTC, igdianov commented on activiti-cloud-runtime-bundle-service/activiti-cloud-services-runtime-bundle/activiti-cloud-services-core/src/main/resources/config/command-endpoint-channels.properties
> +spring.cloud.stream.bindings.commandResults.destination=${ACT_RB_COMMAND_RESULTS_DEST:commandResults}
This is OK. See notes in the PR

2021-10-22 05:55 UTC, igdianov commented on activiti-cloud-runtime-bundle-service/activiti-cloud-services-runtime-bundle/activiti-cloud-services-connectors/src/main/resources/config/integration-result-stream.properties
> +spring.cloud.stream.bindings.integrationErrorsConsumer.destination=integrationError
Yes, this is correct. All channel destinations overrides have been removed.

2021-10-22 05:56 UTC, igdianov commented on activiti-cloud-runtime-bundle-service/activiti-cloud-services-runtime-bundle/activiti-cloud-services-job-executor/src/main/resources/config/job-executor-channel.properties
> -activiti.cloud.rb.job-executor.group=${spring.application.name}
This is OK. The destination suffix is not useful for configuration.

2021-10-22 05:57 UTC, igdianov commented on activiti-cloud-runtime-bundle-service/activiti-cloud-services-runtime-bundle/activiti-cloud-services-subscriptions/src/main/resources/config/signal-events-channels.properties
> +spring.cloud.stream.bindings.signalConsumer.destination=signalEvent
The environment variables for destination overrides are now in messaging properties source

2021-10-22 06:01 UTC, igdianov commented on activiti-cloud-runtime-bundle-service/activiti-cloud-services-runtime-bundle/messages-events/src/main/java/org/activiti/cloud/services/messages/events/config/MessageEventsAutoConfiguration.java
> +        String messageEventOutputDestination = bindingServiceProperties.getBindingDestination("commandConsumer");
Fixed.

2021-10-22 06:02 UTC, igdianov commented on activiti-cloud-runtime-bundle-service/activiti-cloud-services-runtime-bundle/messages-events/src/main/resources/config/messages-events-channels.properties
> -spring.cloud.stream.bindings.messageEvents.destination=messageEvents${activiti.cloud.messaging.destination-separator}${activiti.cloud.application.name}
This is now configured via Activiti messaging destinations properties

2021-10-22 06:04 UTC, igdianov commented on activiti-cloud-runtime-bundle-service/activiti-cloud-starter-runtime-bundle/src/test/java/org/activiti/cloud/starter/tests/conf/EngineConfigurationIT.java
> +                      entry("miCloudConnector", "namespace.micloudconnector"));
fixed

2021-10-22 06:06 UTC, igdianov commented on activiti-cloud-runtime-bundle-service/activiti-cloud-starter-runtime-bundle/src/test/java/org/activiti/cloud/starter/tests/conf/EngineConfigurationIT.java
> +            .isEqualTo(new String[] {"query", "audit"});
fixed

2021-10-22 06:07 UTC, igdianov commented on activiti-cloud-runtime-bundle-service/activiti-cloud-starter-runtime-bundle/src/test/java/org/activiti/cloud/starter/tests/conf/EngineConfigurationIT.java
> +        assertThat(messageEventsOutput.getProducer().getRequiredGroups()).isEqualTo(new String[] {"messages"});
fixed

2021-10-22 06:07 UTC, igdianov commented on activiti-cloud-runtime-bundle-service/activiti-cloud-starter-runtime-bundle/src/test/java/org/activiti/cloud/starter/tests/conf/EngineConfigurationIT.java
> +        assertThat(signalProducer.getProducer().getRequiredGroups()).isEqualTo(new String[] {"my-activiti-rb-app"});
fixed

2021-10-22 06:08 UTC, igdianov commented on activiti-cloud-service-common/activiti-cloud-service-messaging-config/pom.xml
> +      <optional>true</optional>
Yes, the auto-configuration is conditional on `BindingServiceProperties.class` to create bean postprocessor instance.

2021-10-22 06:09 UTC, igdianov commented on activiti-cloud-runtime-bundle-service/activiti-cloud-starter-runtime-bundle/src/main/java/org/activiti/cloud/starter/rb/configuration/ActivitiConnectorDestinationMappingStrategy.java
> +                       .map(messagingProperties.overrideDestination())
Yes, it is used for static and dynamic connector destinations in both places.

2021-10-22 06:10 UTC, igdianov commented on activiti-cloud-service-common/activiti-cloud-service-messaging-config/src/main/java/org/activiti/cloud/common/messaging/ActivitiCloudMessagingProperties.java
> +        return escapeIllegalCharacters().andThen(String::toLowerCase);
I should be able to refactor this after addressing other review points

2021-10-22 06:12 UTC, igdianov commented on activiti-cloud-service-common/activiti-cloud-service-messaging-config/src/main/java/org/activiti/cloud/common/messaging/config/ActivitiMessagingDestinationsBeanPostProcessor.java
> +                               });
Fixed

2021-10-22 06:15 UTC, igdianov commented on activiti-cloud-service-common/activiti-cloud-service-messaging-config/src/main/java/org/activiti/cloud/common/messaging/config/ActivitiMessagingDestinationsBeanPostProcessor.java
> +                                   log.warn("Overriding destination '{}' for binding '{}'",
I think WARN log level is appropriate here:

```
WARN – the log level that indicates that something unexpected happened in the application, a problem, or a situation that might disturb one of the processes. But that doesn’t mean that the application failed. The WARN level should be used in situations that are unexpected, but the code can continue the work. For example, a parsing error occurred that resulted in a certain document not being processed.
```

2021-10-22 06:17 UTC, igdianov commented on activiti-cloud-service-common/activiti-cloud-service-messaging-config/src/test/java/org/activiti/cloud/common/messaging/config/test/ActivitiMessagingDestinationsEnvironmentPostProcessorDisabledTests.java
> +public class ActivitiMessagingDestinationsEnvironmentPostProcessorDisabledTests {
Fixed.

2021-10-22 06:17 UTC, igdianov commented on activiti-cloud-service-common/activiti-cloud-service-messaging-config/src/test/java/org/activiti/cloud/common/messaging/config/test/ActivitiMessagingDestinationsEnvironmentPostProcessorTests.java
> +public class ActivitiMessagingDestinationsEnvironmentPostProcessorTests {
Fixed.

2021-10-22 06:19 UTC, igdianov commented on activiti-cloud-runtime-bundle-service/activiti-cloud-starter-runtime-bundle/src/test/java/org/activiti/cloud/starter/tests/runtime/MQServiceTaskIT.java
> +        assertThat(destinations).containsOnly("mealsConnector",
Let's use contains.

2021-10-22 06:24 UTC, igdianov commented on activiti-cloud-service-common/activiti-cloud-service-messaging-config/src/test/java/org/activiti/cloud/common/messaging/config/test/ActivitiMessagingDestinationsEnvironmentPostProcessorDisabledTests.java
> +    "activiti.cloud.messaging.destinations.[camel-connector.INVOKE].name=${ACT_CAMEL_CONNECTOR_INVOKE_DEST:camel_connector_invoke}",
Connectors only declare consumer channel bindings in the connector process. They don't bother to declare producer channel in Rb because it is created dynamically. However, it is possible to overwrite connector destination using messaging properties for producer and consumer as in this example. 

In addition, the override transformation is only triggered when enabled for both static and dynamic destinations.

2021-10-22 06:27 UTC, igdianov commented on activiti-cloud-service-common/activiti-cloud-service-messaging-config/src/main/java/org/activiti/cloud/common/messaging/config/ActivitiMessagingDestinationTransformer.java
> +public class ActivitiMessagingDestinationTransformer implements Function<String, String> {
The ActivitiMessagingDestinationTransformer is implicitly covered by Spring Boot integration tests. I will add coverage if you think it is needed.

2021-10-22 06:29 UTC, igdianov commented on activiti-cloud-runtime-bundle-service/activiti-cloud-starter-runtime-bundle/src/main/java/org/activiti/cloud/starter/rb/configuration/ActivitiConnectorDestinationMappingStrategy.java
> +        return Optional.ofNullable(destinationTransformer.apply(implementation))
I will refactor this.

2021-10-22 06:45 UTC, igdianov commented
> Igor, you can find my feedback below (don't forget to click on the button "Load more" as there will be hidden comments). One of my main question is about the removal of the suffixes for destinations that has been added during the latest release and documented in the [release notes](https://activiti.gitbook.io/activiti-7-developers-guide/releases/7.1.0-m15#changes-from-previous-milestones).

We will need to update notes for upcoming release to describe new messaging destinations configuration. The channel binding configuration properties have been changed to use new configuration properties. The effective default destination configuration did not change.

2021-10-25 06:58 UTC, igdianov commented on activiti-cloud-runtime-bundle-service/activiti-cloud-starter-runtime-bundle/src/main/java/org/activiti/cloud/starter/rb/configuration/ActivitiConnectorDestinationMappingStrategy.java
> +        return Optional.ofNullable(destinationTransformer.apply(implementation))
Fixed

2021-10-25 06:58 UTC, igdianov commented on activiti-cloud-service-common/activiti-cloud-service-messaging-config/src/main/java/org/activiti/cloud/common/messaging/ActivitiCloudMessagingProperties.java
> +        return escapeIllegalCharacters().andThen(String::toLowerCase);
Fixed

2021-10-25 16:28 UTC, erdemedeiros approved these changes
LTGM!

2021-10-25 16:28 UTC, erdemedeiros commented on activiti-cloud-runtime-bundle-service/activiti-cloud-starter-runtime-bundle/src/test/java/org/activiti/cloud/starter/tests/runtime/MQServiceTaskDestinationsIT.java
> +                  "ACT_MESSAGING_DEST_PREFIX=MQServiceTaskDestinationsIT"})
Could you define a custom value for one of the connectors?

2021-10-26 02:57 UTC, igdianov commented on activiti-cloud-runtime-bundle-service/activiti-cloud-starter-runtime-bundle/src/test/java/org/activiti/cloud/starter/tests/runtime/MQServiceTaskDestinationsIT.java
> +                  "ACT_MESSAGING_DEST_PREFIX=MQServiceTaskDestinationsIT"})
Fixed

2021-10-26 05:59 UTC, merged