[AAE-7467] springdoc swagger
Activiti/activiti-cloud pull request #625
Opened 2022-03-04 09:20 UTC by jsokolowskii

2022-03-04 12:15 UTC, jsokolowskii commented
This PR should wait for Reading Release Train.

2022-03-14 19:05 UTC, VitoAlbano requested changes

2022-03-14 19:05 UTC, VitoAlbano commented on activiti-cloud-audit-service/activiti-cloud-starter-audit/src/test/java/org/activiti/cloud/starter/audit/tests/it/swagger/AuditSwaggerIT.java
> +import static org.hamcrest.Matchers.*;
please avoid starred imports

2022-03-14 19:05 UTC, VitoAlbano commented on activiti-cloud-audit-service/activiti-cloud-starter-audit/src/test/java/org/activiti/cloud/starter/audit/tests/it/swagger/AuditSwaggerIT.java
> +import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
as above

2022-03-14 19:05 UTC, VitoAlbano commented on activiti-cloud-query-service/activiti-cloud-starter-query/src/test/java/org/activiti/cloud/starter/tests/swagger/QuerySwaggerIT.java
> +import static org.hamcrest.Matchers.*;
as above

2022-03-15 15:37 UTC, jsokolowskii commented on activiti-cloud-audit-service/activiti-cloud-starter-audit/src/test/java/org/activiti/cloud/starter/audit/tests/it/swagger/AuditSwaggerIT.java
> +import static org.hamcrest.Matchers.*;
done

2022-03-15 15:37 UTC, jsokolowskii commented on activiti-cloud-audit-service/activiti-cloud-starter-audit/src/test/java/org/activiti/cloud/starter/audit/tests/it/swagger/AuditSwaggerIT.java
> +import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
done

2022-03-15 15:37 UTC, jsokolowskii commented on activiti-cloud-query-service/activiti-cloud-starter-query/src/test/java/org/activiti/cloud/starter/tests/swagger/QuerySwaggerIT.java
> +import static org.hamcrest.Matchers.*;
done

2022-03-15 16:55 UTC, VitoAlbano approved these changes

2022-03-28 12:30 UTC, merged