test(MQServiceTaskIT): add should replay running service task integration test
Activiti/activiti-cloud pull request #887
Opened 2022-10-28 03:02 UTC by igdianov

This PR adds integration test to ensure users can trigger replay for service tasks in started state in case when the integration result message has not been received by process runtime to complete the execution.

2022-10-28 08:24 UTC, erdemedeiros requested changes

2022-10-28 08:24 UTC, erdemedeiros commented on activiti-cloud-runtime-bundle-service/activiti-cloud-starter-runtime-bundle/src/test/java/org/activiti/cloud/starter/tests/runtime/MQServiceTaskIT.java
> +                                 .list()).isEmpty();
Could you, please, also add an assertion to check that no integration context related to this process instance was left behind?

2023-03-15 18:21 UTC, atchertchian commented
If this PR shows conflicts, here are instructions to help rebasing this work branch after reformat at https://github.com/Activiti/activiti-cloud/commit/814a9190ff60af86086e8d111660146569ef6e19:
```
git rebase c845f509770e38aa9663a97cb2f9bcd3e5d39e28
git rebase --strategy-option=theirs --exec 'pre-commit run --from-ref HEAD~ --to-ref HEAD' 814a9190ff60af86086e8d111660146569ef6e19
git rebase develop
```

The last rebase should be omitted if another reformat has happened (similar instructions should be followed for rebase over next reformat).

See more details at https://github.com/Activiti/Activiti/issues/4277.

2023-08-23 07:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Activiti/activiti-cloud?pullRequest=887) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Activiti/activiti-cloud?pullRequest=887) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Activiti/activiti-cloud?pullRequest=887) it.</sub>

2025-01-14 11:01 UTC, eromano commented
@igdianov  do we still need this PR?

2025-01-27 16:31 UTC, closed without merging